name: meshRW tests

on:
  push:
    branches: ['**']
    tags:
      - 'v*'
  pull_request:
    branches: ['**']
  workflow_dispatch:
  schedule:
    - cron: '1 2 */15 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install system dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y libglu1-mesa

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch
          pip install -e .[dev]

      - name: Lint with ruff
        run: |
          ruff check meshRW

      - name: Test with hatch and generate coverage
        run: |
          hatch test --cover
          hatch run coverage xml

      - name: Run tests from installed package context
        run: |
          cwd=$(pwd)
          cd "$(mktemp -d)"
          python -m pytest --pyargs meshRW.tests
          cd "$cwd"

      - name: Prepare coverage badge folder
        if: ${{ matrix.python-version == '3.13' }}
        run: mkdir -p coverage

      # - name: Generate coverage badge
      #   if: ${{ matrix.python-version == '3.13' }}
      #   uses: tj-actions/coverage-badge-py@v2
      #   with:
      #     output: coverage/coverage.svg

      - name: Coverage Badge
        if: ${{ matrix.python-version == '3.13' }}
        run: |
          pip install -U genbadge[coverage]
          genbadge coverage -i  reportcov/report.xml -o coverage/coverage.svg

      - name: Publish coverage badge branch
        if: ${{ matrix.python-version == '3.13' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: coverage-badge
          folder: coverage